# Generated by Django 4.2.13 on 2024-06-12 12:11

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_description_remove_hotel_tags_hotel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
