# Generated by Django 4.2.13 on 2024-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
